parameters:
    mucho_mas_facil_form_by_email.class: MuchoMasFacil\FormByEmailBundle\Service\FormByEmail
    mucho_mas_facil_form_by_email.definitions: 
        default:
            template: MuchoMasFacilFormByEmailBundle:Default:formByEmail.txt.twig                
            locale: ~
            translation_domain: messages
            skip_fields: [_token]
            #below those used by sendMail itself
            is_html: false    
            sender_setFrom: []
            sender_setSender: ~ 
            sender_setReturnPath: ~ 
            sender_setReplyTo: ~ 
            recipients_setTo: []
            recipients_setCc: []
            recipients_setBcc: []
            recipients_addTo: []
            recipients_addCc: []
            recipients_addBcc: []
        

services:
    mmf_form_by_email:
        class: "%mucho_mas_facil_form_by_email.class%"
        arguments: ["@service_container"]
