parameters:
#    mucho_mas_facil_form_by_email.example.class: MuchoMasFacil\FormByEmailBundle\Example

services:
#    mucho_mas_facil_form_by_email.example:
#        class: %mucho_mas_facil_form_by_email.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
